### ISSUE TITLE
[Epic] Last minute Application UI tweaks

### ISSUE THREAD

**Issue by SherRao** [LaurierHawkHacks/Dashboard#292]
Branch for all these changes can be found here: https://github.com/LaurierHawkHacks/Dashboard/tree/last-min-app-tweaks

- [x] Change the button text from "Apply to Hackathon" to "Start your application"
- [x] Reposition the  "Apply to Hackathon" button to look better.
- [x] Change the title of the route from "Home" to "Application"
- [x] Once an app is submitted, the original "Apply to Hackathon" button should be grayed out
- [x] Once an app is submitted, add text below the apply button with the prompt "Had issues with your application? **Resubmit one here**.”
